language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0

# Use RubyGems 1.8 since 2.0 doesn't work with Chef
before_install: gem update --system 1.8.25

install:
  - curl -Ls https://jimdo-travisci.s3.amazonaws.com/skeleton-cookbook/gems.tar | tar -xv
  - bundle install --local

script: bundle exec rake test:travis

branches:
  only:
    - master
